import Head from "next/head";
import { FC, ReactNode } from "react";
import { Header } from "src/components/organisms/Header";
import { Footer } from "src/components/organisms/Footer";
import styled from "styled-components";
import { TopContent } from "../organisms/TopContent";

type Props = {
  title: string;
  children: ReactNode;
};

export const Template: FC<Props> = ({ title, children }) => (
  <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header></Header>
    <TopContent />
    {children}
    <Footer></Footer>
  </>
);
